name: Homefay
options:
  bundleIdPrefix: com.agungsptr
  settings:
    iOS:
      TARGETED_DEVICE_FAMILY: "1" # 1 for iPhone, 2 for iPad
targets:
  Homefay:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Homefay
    info:
      path: App/Info.plist
      properties:
        UILaunchScreen: LaunchScreen
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    settings:
      CODE_SIGN_ENTITLEMENTS: Homefay/Homefay.entitlements
  HomefayWatch Watch App:
    type: watch2App
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - HomefayWatch Watch App
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
